# -*- coding: utf-8 -*-
"""Resistor_Identifier_valueCalulator_CNN _Code.ipynb

Automatically generated by Colab.
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
from google.colab import drive

import cv2
import numpy as np


drive.mount('/content/drive')


BASE_PATH = "/content/drive/MyDrive/Colab Notebooks/Machine Vision - Resistor Identifier/cnn_dataset"


train_dir = BASE_PATH + "/train"

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=(128, 128),
    batch_size=32,
    label_mode='binary'
)

print("Class names:", train_ds.class_names)

import os
for cls in train_ds.class_names:
    folder = os.path.join(train_dir, cls)
    print(cls, "contains", len(os.listdir(folder)), "files")

normalization_layer = layers.Rescaling(1./255)
train_ds = train_ds.map(lambda x, y: (normalization_layer(x), y))





model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # binary output
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()


class_weight = {
    0: 2830 / 11,  # no_resistor (rare → heavy penalty)
    1: 1.0        # resistor
}


history = model.fit(
    train_ds,
    epochs=10,
    class_weight=class_weight
)



plt.plot(history.history['accuracy'], label='train')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()




def cnn_resistor_present(image_path, model):
    img = tf.keras.utils.load_img(image_path, target_size=(128,128))
    img = tf.keras.utils.img_to_array(img) / 255.0
    img = tf.expand_dims(img, 0)

    prob_no_resistor = model.predict(img, verbose=0)[0][0]

    resistor_confidence = 1.0 - prob_no_resistor
    resistor_present = resistor_confidence > 0.5

    return resistor_present, resistor_confidence



import os

UNKNOWN_TEST_DIR = BASE_PATH + "/test"

for filename in os.listdir(UNKNOWN_TEST_DIR):
    if not filename.lower().endswith(('.jpg', '.png', '.jpeg')):
        continue

    image_path = os.path.join(UNKNOWN_TEST_DIR, filename)

    present, confidence = cnn_resistor_present(image_path, model)

    label = "Resistor present" if present else "No resistor"
    print(f"{filename}: {label} (confidence={confidence:.2f})")




def crop_resistor(img_bgr):
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150)

    kernel = np.ones((5,5), np.uint8)
    edges = cv2.dilate(edges, kernel)

    contours, _ = cv2.findContours(
        edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    best = None
    max_len = 0

    for c in contours:
        rect = cv2.minAreaRect(c)
        (cx, cy), (w, h), angle = rect

        length = max(w, h)
        thickness = min(w, h)

        # Geometry rules for a resistor
        if length > max_len and thickness > 8 and length / max(1, thickness) > 4:
            max_len = length
            best = rect

    if best is None:
        h, w = img_bgr.shape[:2]
        return img_bgr[h//4:3*h//4, w//8:7*w//8]

    box = cv2.boxPoints(best)
    box = box.astype(int)

    x, y, w, h = cv2.boundingRect(box)
    return img_bgr[y:y+h, x:x+w]



COLOR_RANGES = {
    'black':  ((0, 0, 0),    (180, 255, 50)),    # low V
    'brown':  ((8, 60, 20),  (20, 200, 160)),
    'red':    ((0, 80, 80),  (10, 255, 255)),
    'yellow': ((18, 80, 120),(32, 255, 255)),
    'green':  ((40, 50, 50), (85, 255, 255)),
    'blue':   ((90, 60, 50), (135, 255, 255)),
    'violet': ((135, 50, 50),(160, 255, 255)),
    'gold':   ((15, 40, 100),(35, 180, 255)),   # low S, high V
    'silver': ((0, 0, 150),  (180, 60, 255))    # very low S
}



from google.colab.patches import cv2_imshow

print("\n--- Band detection stage ---")

from collections import Counter

def merge_close_bands(bands, min_dx=30):
    """
    bands: list of (x, color)
    returns: list of (x_mean, color, votes)
    """
    merged = []

    for x, color in sorted(bands):
        if not merged:
            merged.append([x, color, 1])
        else:
            last = merged[-1]
            if abs(x - last[0]) < min_dx:
                last[0] = (last[0] * last[2] + x) / (last[2] + 1)
                last[2] += 1
            else:
                merged.append([x, color, 1])

    return merged

def select_final_bands(bands_with_votes, target=5):

    # Sort by vote strength
    bands_sorted = sorted(bands_with_votes, key=lambda b: b[2], reverse=True)

    # Keep only strongest candidates
    bands_sorted = bands_sorted[:max(target, len(bands_sorted))]

    # Re-sort left → right
    bands_sorted = sorted(bands_sorted, key=lambda b: b[0])

    colors = [b[1] for b in bands_sorted]

    # Force tolerance band to the end if present
    for tol in ['gold', 'silver']:
        if tol in colors:
            colors.remove(tol)
            colors.append(tol)
            break

    return colors[:target]

def calculate_resistance(colors):
    if len(colors) == 5:
        d1, d2, d3, mult, tol = colors
        value = (DIGITS[d1]*100 + DIGITS[d2]*10 + DIGITS[d3]) * MULTIPLIER[mult]
        tolerance = TOLERANCE.get(tol, 'unknown')
        return f"{value:.2g} Ω {tolerance}"

    elif len(colors) == 4:
        d1, d2, mult, tol = colors
        value = (DIGITS[d1]*10 + DIGITS[d2]) * MULTIPLIER[mult]
        tolerance = TOLERANCE.get(tol, 'unknown')
        return f"{value:.2g} Ω {tolerance}"

    else:
        return "Unreliable detection"

DIGITS = {
    'black':0, 'brown':1, 'red':2, 'orange':3,
    'yellow':4, 'green':5, 'blue':6,
    'violet':7, 'grey':8, 'white':9
}

MULTIPLIER = {
    'black':1, 'brown':10, 'red':100, 'orange':1_000,
    'yellow':10_000, 'green':100_000, 'blue':1_000_000,
    'violet':10_000_000, 'gold':0.1, 'silver':0.01
}

TOLERANCE = {
    'brown':'±1%', 'red':'±2%', 'green':'±0.5%',
    'blue':'±0.25%', 'violet':'±0.1%',
    'gold':'±5%', 'silver':'±10%'
}

for filename in os.listdir(UNKNOWN_TEST_DIR):
    if not filename.lower().endswith(('.jpg', '.png', '.jpeg')):
        continue

    image_path = os.path.join(UNKNOWN_TEST_DIR, filename)

    img_bgr = cv2.imread(image_path)
    if img_bgr is None:
        print(f"{filename}: failed to load")
        continue

    resistor_crop = crop_resistor(img_bgr)

    if resistor_crop.size == 0:
        print(f"{filename}: empty crop")
        continue

    hsv = cv2.cvtColor(resistor_crop, cv2.COLOR_BGR2HSV)

    bands = []

    for color, (lower, upper) in COLOR_RANGES.items():
        if color == 'red':
          mask1 = cv2.inRange(hsv, (0, 70, 50), (10, 255, 255))
          mask2 = cv2.inRange(hsv, (170, 70, 50), (180, 255, 255))
          mask = cv2.bitwise_or(mask1, mask2)
        else:
          mask = cv2.inRange(hsv, np.array(lower), np.array(upper))

        kernel = np.ones((3,3), np.uint8)
        mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
        mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)

        contours, _ = cv2.findContours(
            mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for c in contours:
            x, y, w, h = cv2.boundingRect(c)
            if 0.1 * resistor_crop.shape[0] < h < 0.9 * resistor_crop.shape[0] and w < 0.5 * resistor_crop.shape[1]:
                bands.append((x, color))


    print(f"{filename}: Detected bands ->", bands)

    merged = merge_close_bands(bands)

    final_colors = select_final_bands(merged, target=5)
    result = calculate_resistance(final_colors)

    print(f"{filename}: Final bands -> {final_colors}")
    print(f"{filename}: Resistor value =", result)

    cv2_imshow(resistor_crop)

